#############################################################################################################
##   _______   _                      __     __             _    
##  / ___/ /  (_)__  __ _  __ _____  / /__  / /  ___  ___ _(_)___ TM
## / /__/ _ \/ / _ \/  ' \/ // / _ \/  '_/ / /__/ _ \/ _ `/ / __/          ////  O P E N - S O U R C E ////
## \___/_//_/_/ .__/_/_/_/\_,_/_//_/_/\_\ /____/\___/\_, /_/\__/ 
##           /_/                                    /___/              
#############################################################################################################
# Script           : pqr5 generate RAM wrapper
# Developer        : Mitu Raj, chip@chipmunklogic.com
# Vendor           : Chipmunk Logic™, https://chipmunklogic.com
#
# Description      : This script is used by Makefile to generate wrappers over the generated IRAM & DRAM.
#                    All arguments are assumed to be valid values from Makefile.
#
# Last modified on : Aug-2024
# Compatiblility   : Python 3.9 tested
#
# Copyright        : Open-source license, see LICENSE.
#############################################################################################################

# Import libraries
import sys

# Read all command line arguments, open all reqd. files
fin_path   = sys.argv[1]
gen_module = sys.argv[2]
ram_depth  = sys.argv[3]       
ram_width  = sys.argv[4]      
type       = sys.argv[5]
fin = open(fin_path, "rt")
fout_path = fin_path.replace('\\', '/')
fout_path_l = list(fout_path.split('/'))
fout_path_l [-1] = ''
fout_path = "/".join(fout_path_l) + str(gen_module) + '.sv'
fout = open(fout_path, "wt")

if type == "0":
	depthparam = 'DEPTH'
else:
	depthparam = 'RAM_DEPTH'

# Source content, destination content
src = fin.read().splitlines()
des = []

# Analyze each line and modify depth and width
for line in src:
	if line.startswith('module'):
		des.append('module ' + gen_module + '#(')    
	elif len(line.split()) > 0 and line.split()[0] == 'parameter' and line.split()[1] == depthparam:
		des.append('   parameter  '+ depthparam + '  = ' + str(ram_depth) + ' ,    // Depth of RAM //**AUTOGENERATED**//')
	elif len(line.split()) > 0 and line.split()[0] == 'parameter' and line.split()[1] == 'DATA_W':
		des.append('   parameter  DATA_W = ' + str(ram_width) + ' ,    // Data width //**AUTOGENERATED**//')
	else:
		des.append(line)      

# Write to destination file
for line in des:
	#print(line)
	fout.write(line + '\n')  # Because string list doesn't contain '\n' characters, all trimmed by  splitline()

# Close all files
fin.close()
fout.close()
if type == "0":
	print ('| GENWRAP: Successfully generated wrapper for IRAM ...')
else:
	print  ('| GENWRAP: Successfully generated wrapper for DRAM ...')